### PR TITLE
enforce sibling sum check

### LINKED ISSUE #4: non negative siblingsSum is required in the circom
There's no guarantee that the `siblingsSum >= 0` in the current circom.
LessEqThan should be enforced on this input for each iteration

### PR DESCRIPTION
**Pull request by wlbksy**
fix https://github.com/pan-y-tomate/prover/issues/4

### CODE REVIEW

**Comment by enricobottazzi** [comment]
Hi, thanks for the PR. A negative `sibling sum`, such as -1, used as input to the circuit would not be interpreted as a negative value as negative values do not exist in the Field Group `p` where the snark operates. Instead, it should be interpreted as `p-1`.  Testing it I noticed that in practice it gets interpreted as `2**32 - 1`. I don't know why and I asked it into the iden3 tg group. Considering this, adding a negative value as input would increase the liabilities of the exchange, which is a huge disincentive. Because of that, I don't believe that this fix is needed.

**Comment by wlbksy** [comment]
Interesting. A negative number would have the most significant bit as `1`, which would fail `LessThan(252)` called by `LessEqThan(252)`   https://github.com/iden3/circomlib/blob/master/circuits/comparators.circom

**Comment by wlbksy** [comment]
> used as input to the circuit would not be interpreted as a negative value as negative values do not exist in the Field Group p where the snark operates. Instead, it should be interpreted as p-1. Testing it I noticed that in practice it gets interpreted as 2**32 - 1

As for negative number, this is not where  Field Group evolved. It's simply circuits/bits two's complement representation. I wander why it's 2^{32}-1 instead of 2^{256}-1. Which platform did you test on?

**Comment by enricobottazzi** [comment]
> Which platform did you test on?

Using circom 2.0.9 I tested it passing this input
```json
{
    "a": -1
}
``` 

to this circuit 
```circom
pragma circom 2.0.9;

include "node_modules/circomlib/circuits/comparators.circom";

template AssertLt() {

    signal input a;

    log(a);

    component lt = LessThan(252);
    
    lt.in[0] <== a;
    lt.in[1] <== 0;
    log(lt.out);
}

component main = AssertLt();
```

The logs are 
```
4294967295
0
```

> A negative number would have the most significant bit as 1, which would fail LessThan(252) called by LessEqThan(252) 

That wouldn't always be the case. Admitting that `-z` is wired in the circuit as `p-z` and assigning `z = p - 1`,   
 `-z = p - p + 1 = +1` which would not fail LessThan(252) .

Also, going back to the core purpose of this library, the only security measure it needs to enforce is that the sum of the values of two leaves is performed correctly. Since no negative values are accepted inside the circuit, inputting a negative value will only increase the sum so it is a disincentive for the prover exchange. The only way it could go wrong is if the sum overflows the prime. To solve that, I aim to add a [RangeCheck](https://github.com/sismo-core/hydra-s1-zkps/blob/main/circuits/hydra-s1.circom#L101) over the addendums of the sum.

**Comment by wlbksy** [comment]
I dig it a little bit, and you're right on the result: circom does not take assumptions on how many bits the input has. 
And this means negative balance check  using LessThan 0 is not valid. We should use Range Check indeed.

This pr doesn't fix the issue. I'll close it.

**Pull request closed without merging**
